### ISSUE TITLE
Space between modifier and value

### ISSUE THREAD

**Issue by taion** [ianstormtaylor/css-color-function#18]
According to the note on https://drafts.csswg.org/css-color/#modifying-colors:

>Note: While scaling can be specified without any spaces, like lightness(*150%), adding/subtracting must be done with spaces after the +/-, or else the +/- will be interpreted as part of the number by the CSS parser.

This suggests that the `+` or `-` modifiers should only be parsed as such if there is a space between the modifier and the modified value. This is not the current behavior of the parser.

Am I missing something here?

**Comment by kinday** [comment]
Hi, @taion!

You’re absolutely right! For example, [this test](https://github.com/ianstormtaylor/css-color-function/blob/master/test/convert.js#L224) should fail according to spec.

Do you want to fix that behavior?

**Comment by taion** [comment]
cc @jquense

While it would be possible to do that, in practice it would probably be badly breaking to many users.

I was really, really surprised to find out that the spec even said to do this.

Is there any better approach here?

**Comment by kinday** [comment]
Of course, it is a breaking change, but this module is a spec implementation, so we should follow it.

There is no backward-compatible way to fix it, so to be thoughtful, we’ll release a major update.

**Comment by MoOx** [comment]
+1 for the major release.
