### ISSUE TITLE
The `color` function is renamed to `color-mod`

### ISSUE THREAD

**Issue by jonathantneal** [ianstormtaylor/css-color-function#29]
See https://drafts.csswg.org/css-color/#modifying-colors

The new name, for now, is `color-mod` because `color` is going to mean something else. The new name may also change, but it would likely **not** to return to being `color`, as that function name has its own new meaning.

See also: https://github.com/w3c/csswg-drafts/issues/813#issuecomment-268252981

**Comment by tylergaw** [comment]
There's a working draft of this now https://www.w3.org/TR/css-color-4/#modifying-colors. All the examples still show `color()` instead of `color-mod()`. @jonathantneal Do you think that's still just leftover from before and the idea is that they'll eventually be updated?

I'm thinking through doing a 2.x of css-color-function to change the naming, but don't want to jump the gun.

**Comment by tylergaw** [comment]
@jonathantneal Added a "paused" label to this because we'll want to hold off. Got word from the spec editor that we should wait.

> Basically ignore the color-mod() function for now. It needs to be substantially revamped.

over in https://github.com/ianstormtaylor/css-color-function/pull/33#issuecomment-334899220

**Comment by jonathantneal** [comment]
@tylergaw, after some conversation and review, it seems pretty clear that the name will not be `color()`, and that the current spec name is `color-mod()`.

> color is now color-mod because color is now something a little different.
> color() here -> https://www.youtube.com/watch?v=PqDw0ZPYIq8&t=25m59s
> — [@evaferreira92](https://twitter.com/evaferreira92/status/905035717671362560)

The lingering presence of the old name was due to...

> Just hasty renaming. color-mod needs a new syntax and, possibly, a new name. Meanshile it needs a do-not-implement notice on that section.
> — https://github.com/w3c/csswg-drafts/issues/813#issuecomment-268252981

So, we can:

1. heed the *do-not-implement* notice and, idk, deprecate the project
2. politely ignore the notice but honor the name change because this is a speculative polyfill and that means things can change wildly
3. ignore the notice, ignore the the name change (call it a polyfill or not, it’d be a library now) and forgo spec compatibility in exchange for backwards compatibility with existing users (which totally has its appeal), or
4. something I haven’t thought of, idk, like making it an option to pick the name or forking the spec? :)

Truly, I don’t think there’s a wrong answer, but I am personally afraid of answer # 3.

**Comment by tylergaw** [comment]
Hrmmm, thanks @jonathantneal. I'll watch that video and do some more reading to form a more informed opinion, but first reaction, I kinda like the spirit of answer # 3 there! Even if that's not exactly how it shakes out. Here's why I like the spirit / idea:

The spec(s) around CSS color are obviously in development and we're super early adopters. We've reach a point where I think we can help guide the spec on this feature set. Like you mentioned, people are using this already and have been for some time. As always, the spec(s) need to pave the cowpaths and meet CSS authors where they are. That's not to say we won't need to change how we've been doing things, but there should be some give and take.

Personal opinion as a CSS author, I'm not a huge fan of `color-mod` as the function name. It's clunky to type and reads like an internal function of some sort. It also seems a bit inconsistent with other newer function names like; `repeat`, and `minmax`. However there is the `fit-content` function, so not out of nowhere.

I'll get myself more informed and come back.

**Comment by jonathantneal** [comment]
@tylergaw, thanks for reading, and for the fast response. The *long name* issue is legitimate, and in one of those GitHub threads you can even see them entertain repurposing `calc()`.

All that being said, I couldn’t in good conscience bump a major release of any polyfill library that used the wrong name for the spec, especially if that name is now taken by another feature.

**Comment by Jessidhia** [comment]
To clarify for people that can't/won't watch the video: `color()` is proposed, and already implemented by Apple, for declaring colors according to a color profile (wide gamut colors). Examples: `color(display-p3 1.0 1.0 1.0)`; `color(my-profile 0 .5 .6 .7); @color-profile my-profile { src: url('/profile.icc'); }`.

**Comment by jonathantneal** [comment]
@Kovensky, @tylergaw, https://github.com/ianstormtaylor/css-color-function/pull/35

**Comment by jonathantneal** [comment]
All old references to `color()` have been removed from the working spec. I’m sorry this discussion was never resolved, but to be fair I’m not sure many people are actively continuing the discussion.

https://drafts.csswg.org/css-color-4/#modifying-colors

**Comment by MoOx** [comment]
Why do you close this issue? It should be handled somehow.

**Comment by jonathantneal** [comment]
I referenced my PR 3 months ago. There is nothing to add here.
