### ISSUE TITLE
Vulnerability - Regular Expression Denial of Service

### ISSUE THREAD

**Issue by finnhvman** [ianstormtaylor/css-color-function#30]
I am using a package which indirectly depends on this (css-color-function) package. The Node Security Platform detected a vulnerability in the debug package dependency.

Can you please update the **version** of the **debug** dependency to a secure one?

More info: [https://nodesecurity.io/advisories/534](https://nodesecurity.io/advisories/534)

**Comment by ndaidong** [comment]
@finnhvman I got the same issue with postcss-cssnext@3.0.2

**Comment by tylergaw** [comment]
@finnhvman @ndaidong Okie dokie, this is fixed and released in 1.3.2 https://github.com/ianstormtaylor/css-color-function/releases/tag/1.3.2

One thing noted in the release there that I'll mention again. That version is not yet available on npm you'll need to install from the git tag. I don't have npm publish access yet, only @ianstormtaylor

**Comment by MoOx** [comment]
@tylergaw you have the proper right on npm https://www.npmjs.com/package/css-color-function !

**Comment by tylergaw** [comment]
Oh snap! I didn't realize. Cool, will get that published today. Thanks!

**Comment by finnhvman** [comment]
Awesome! Thx for the help! 🎉
