### ISSUE TITLE
Breaking change with major release

### ISSUE THREAD

**Issue by ai** [ianstormtaylor/css-color-function#32]
This change https://github.com/ianstormtaylor/css-color-function/commit/9334b306bef20ab1b0a61706cce222ee3bfb2ed6 is breaking change and it is very sensitive without ChangeLog.

Maybe we can add ChangeLog? Or some warning?

**Comment by tylergaw** [comment]
We have this https://github.com/ianstormtaylor/css-color-function/blob/master/History.md file, but I don't see any mention of that change. Followed a path there and found the original issue https://github.com/ianstormtaylor/css-color-function/issues/18 and the PR https://github.com/ianstormtaylor/css-color-function/pull/19

The breaking changes were discussed in that issue. Looks like the idea there was to release that in a 2.x series, but that didn't happen.

Looks like that change went out in 1.3.1 https://github.com/ianstormtaylor/css-color-function/releases/tag/1.3.1 That was my first contribution, durn. I didn't know about the regex change in there.

**Comment by ai** [comment]
Maybe we can revert changes in 1.3.3 and release them in 2.0?

I afraid right now many users see that their CSS for `postcss-color-function` is broken.

**Comment by ai** [comment]
Also, don’t worry, making revert releases is OK :). I know your fillings with wrong changes in release :).

**Comment by tylergaw** [comment]
OK, yeah that all sounds good to me. I'll get the revert to a PR and ping you on that.

**Comment by ianstormtaylor** [comment]
@tylergaw thank you for all the time you've invested in helping with this library!

**Comment by tylergaw** [comment]
@ianstormtaylor Absolutely! I'm happy to be able to help out with it.
